### ISSUE TITLE
InvalidConfigurationException - short notation for role names

### ISSUE THREAD

**Issue by jrenggli** [svparijs/TYPO3.AccountManagement#15]
Hi

Got the following exception after installing TYPO3.AccountManagement

```
  Uncaught Exception:
  TYPO3\Flow\Configuration\Exception\InvalidConfigurationException

  Message
    Roles defined in a package policy must not be qualified (that is, using
    the dot notation), but the role "TYPO3.AccountManagement:Administrator"
    is (in package "TYPO3.AccountManagement"). Please use the short
  notation
    with only the role name (for example "Administrator").
```

**Comment by jrenggli** [comment]
This change was introduced in the following commit https://github.com/svparijs/TYPO3.AccountManagement/commit/fc5c842fd6d695ea41ee1cd31d73b2e40899e54d
TYPO3 Flow 3.0.0-beta1 needs this new format.

**Comment by svparijs** [comment]
Hi @jrenggli, I've updated the configuration to handle TYPO3 Flow version 3.0, and tagged the working version for TYPO3 Flow version 2.3.*

Please use: "typo3/accountmanagement": "1.0.1" to get the proper configuration working again.
